name: mova
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  loading_indicator: ^3.1.0
  dartz: ^0.10.1
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.2.1
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.12  

  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/logo.png
  background_image: assets/images/s_background.png

  
flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-Light.ttf
          weight: 300
        - asset: assets/fonts/Teko-Regular.ttf
          weight: 400
        - asset: assets/fonts/Teko-Medium.ttf
          weight: 500
        - asset: assets/fonts/Teko-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Teko-Bold.ttf
          weight: 700

    - family: StickNoBills
      fonts:
        - asset: assets/fonts/StickNoBills-Light.ttf
          weight: 300
        - asset: assets/fonts/StickNoBills-Regular.ttf
          weight: 400
        - asset: assets/fonts/StickNoBills-Medium.ttf
          weight: 500
        - asset: assets/fonts/StickNoBills-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/StickNoBills-Bold.ttf
          weight: 700
        
